version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tic_tac_toe
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./tic-tac-toe-backend
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/tic_tac_toe

  frontend:
    build: ./tic-tac-toe-frontend
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://localhost:5000"

volumes:
  db-data:
